http:
  port: 3003

logger: # 로그 레벨 설정, 필요 없는 레벨 지우거나 주석처리하기
  # - log
  - debug
  # - error
  # - warn
  # - verbose

db: # Database connection 설정
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'password'
  # 절대 dev 또는 prod 와 같은 database schema name 이어서는 안된다.
  # 동일할 시, dev 또는 prod 의 table 이 전부 날아갈 수 있음
  database: 'test_schema'
  synchronize: true
  dropSchema: true
  timezone: 'Z'