http:
  port: 3001

logger: # 로그 레벨 설정, 필요 없는 레벨 지우거나 주석처리하기
  # - log
  - debug
  # - error
  # - warn
  # - verbose

db: # Database connection 설정
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'password'
  database: 'database_development'
  synchronize: true
  timezone: 'Z'